[project]
name = "jonsim.com-dev-workspace"
version = "0.0.0"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
dev = [
    "pre-commit==4.5.1",
    "blog-render",
    "cook-render",
]

[tool.uv]
package = false

[tool.uv.workspace]
members = [
    "tools/blog-render",
    "tools/cook-render",
]

[tool.uv.sources]
blog-render = { workspace = true }
cook-render = { workspace = true }
